/home/a/ghc-7.8.3/inplace/lib/bin/haddock -B/home/a/ghc-7.8.3/inplace/lib -l/home/a/ghc-7.8.3/inplace/lib --odir=libraries/xhtml/dist-install/doc/html/xhtml --no-tmp-comp-dir --dump-interface=libraries/xhtml/dist-install/doc/html/xhtml/xhtml.haddock --html --hoogle --title=xhtml-3000.2.1: An XHTML combinator library --prologue=libraries/xhtml/dist-install/haddock-prologue.txt --hide=Text.XHtml.Strict.Attributes --hide=Text.XHtml.Strict.Elements --hide=Text.XHtml.Frameset.Attributes --hide=Text.XHtml.Frameset.Elements --hide=Text.XHtml.Transitional.Attributes --hide=Text.XHtml.Transitional.Elements --hide=Text.XHtml.BlockTable --hide=Text.XHtml.Extras --hide=Text.XHtml.Internals --read-interface=../base-4.7.0.1,../base-4.7.0.1/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --optghc=-hisuf --optghc=dyn_hi --optghc=-osuf --optghc=dyn_o --optghc=-hcsuf --optghc=dyn_hc --optghc=-fPIC --optghc=-dynamic --optghc=-H32m --optghc=-O --optghc=-package-name --optghc=xhtml-3000.2.1 --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/xhtml/. --optghc=-ilibraries/xhtml/dist-install/build --optghc=-ilibraries/xhtml/dist-install/build/autogen --optghc=-Ilibraries/xhtml/dist-install/build --optghc=-Ilibraries/xhtml/dist-install/build/autogen --optghc=-Ilibraries/xhtml/. --optghc=-optP-include --optghc=-optPlibraries/xhtml/dist-install/build/autogen/cabal_macros.h --optghc=-package --optghc=base-4.7.0.1 --optghc=-Wall --optghc=-XHaskell98 --optghc=-XCPP --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/xhtml/dist-install/build --optghc=-hidir --optghc=libraries/xhtml/dist-install/build --optghc=-stubdir --optghc=libraries/xhtml/dist-install/build --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/xhtml/./Text/XHtml.hs libraries/xhtml/./Text/XHtml/Frameset.hs libraries/xhtml/./Text/XHtml/Strict.hs libraries/xhtml/./Text/XHtml/Transitional.hs libraries/xhtml/./Text/XHtml/Debug.hs libraries/xhtml/./Text/XHtml/Table.hs libraries/xhtml/./Text/XHtml/Strict/Attributes.hs libraries/xhtml/./Text/XHtml/Strict/Elements.hs libraries/xhtml/./Text/XHtml/Frameset/Attributes.hs libraries/xhtml/./Text/XHtml/Frameset/Elements.hs libraries/xhtml/./Text/XHtml/Transitional/Attributes.hs libraries/xhtml/./Text/XHtml/Transitional/Elements.hs libraries/xhtml/./Text/XHtml/BlockTable.hs libraries/xhtml/./Text/XHtml/Extras.hs libraries/xhtml/./Text/XHtml/Internals.hs +RTS -tlibraries/xhtml/dist-install/doc/html/xhtml/xhtml.haddock.t --machine-readable 
 [("bytes allocated", "514610656")
 ,("num_GCs", "293")
 ,("average_bytes_used", "11657840")
 ,("max_bytes_used", "24589608")
 ,("num_byte_usage_samples", "7")
 ,("peak_megabytes_allocated", "65")
 ,("init_cpu_seconds", "0.00")
 ,("init_wall_seconds", "0.00")
 ,("mutator_cpu_seconds", "0.32")
 ,("mutator_wall_seconds", "0.51")
 ,("GC_cpu_seconds", "0.33")
 ,("GC_wall_seconds", "0.38")
 ]
